social_auth_apple.settings:
  type: config_object
  label: 'Social Auth Apple settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    team_id:
      type: string
      label: 'Team Id'
    key_file_id:
      type: string
      label: 'Key File ID'
    key_file_path:
      type: string
      label: 'Key File Path'
